language: node_js
node_js:
  - "5"
  - "6"
install:
  - yarn install
script:
  - yarn run validate
  - yarn run build
after_success:
  - yarn test
  - yarn run coveralls
  - yarn run codecov
  - yarn run github-release
cache: yarn
