language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"
install:
  - npm install
script:
  - npm run check
  - npm run build
  - npm run validate
after_success:
  - npm run coveralls
  - npm run github-release
